### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by ManlioWu** [lucidrains/graph-transformer-pytorch#4]
Hi, I used your code in my research, and when I introduce this part, how can I cite it? Thanks!

**Comment by lucidrains** [comment]
@ManlioWu no need to cite! just send me a link to your arxiv paper when you are done

**Comment by ManlioWu** [comment]
> @ManlioWu no need to cite! just send me a link to your arxiv paper when you are done

Okay, Thank you! I will send the link to you after my work is finished
